version: "3.9"
services:
  backend:
    build: ./backend
    container_name: ibge-backend
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: ibge-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
